name: Collect binary files

#on:
#  push:
#    tags:
#      - 'v*'

on: [push]

jobs:
  get-docs:
    steps:

    - name: Download documentation
      uses: dawidd6/action-download-artifact@v2
      with:
        # Optional, GitHub token
        github_token: ${{secrets.GITHUB_TOKEN}}
        # Required, workflow file name or ID
        workflow: docs.yml
        # Optional, the status or conclusion of a completed workflow to search for
        # Can be one of a workflow conclusion::
        # "failure", "success", "neutral", "cancelled", "skipped", "timed_out", "action_required"
        # Or a workflow status:
        # "completed", "in_progress", "queued"
        # Default: "completed"
        workflow_conclusion: success
        # Optional, no need to specify if PR is
        commit: ${{github.event.pull_request.head.sha}}

    - name: Download binaries
      uses: dawidd6/action-download-artifact@v2
      with:
        # Optional, GitHub token
        github_token: ${{secrets.GITHUB_TOKEN}}
        # Required, workflow file name or ID
        workflow: ci.yml
        # Optional, the status or conclusion of a completed workflow to search for
        # Can be one of a workflow conclusion::
        # "failure", "success", "neutral", "cancelled", "skipped", "timed_out", "action_required"
        # Or a workflow status:
        # "completed", "in_progress", "queued"
        # Default: "completed"
        workflow_conclusion: success
        # Optional, no need to specify if PR is
        commit: ${{github.event.pull_request.head.sha}}

    - name: Upload Modelica folder with PDF
      uses: actions/upload-artifact@v1
      with:
        name: binaries
        path: Modelica
